<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thm</name>
   <tag></tag>
   <elementGuidId>4158b2f6-6b01-4a49-a429-c813cd942d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.el-button.is-create-color.is-white.is-none-border.icon-btn.p-0.m-0.el-button--default.el-popover__reference.focusing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a055dfb2-7e74-4cf4-b32d-510bc8cbf93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94c35742-ed68-433e-9269-7d1cbba0a295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button is-create-color is-white is-none-border icon-btn p-0 m-0 el-button--default el-popover__reference focusing</value>
      <webElementGuid>2cd2ceb7-f1df-473e-8388-434bd7b826e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popover-3215</value>
      <webElementGuid>70e2a36a-fd83-48f0-9703-74579899f1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b42f8051-ddab-44f1-ab44-29c705141563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thêm</value>
      <webElementGuid>e1a169a5-bd65-41b5-8f96-f0faef377dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;side-menu&quot;]/ul[@class=&quot;list-menu&quot;]/li[@class=&quot;layout-add-menu&quot;]/span[1]/span[@class=&quot;el-popover__reference-wrapper&quot;]/button[@class=&quot;el-button is-create-color is-white is-none-border icon-btn p-0 m-0 el-button--default el-popover__reference focusing&quot;]</value>
      <webElementGuid>c1d1ec1f-2c70-4c8b-ae05-8cf9803fbf14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>37b02417-7f1f-4982-871f-55c057f2d604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/ul/li[7]/span/span/button</value>
      <webElementGuid>b6b15f5b-b9b7-4722-b120-9387ba61de95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhà mình'])[1]/following::button[1]</value>
      <webElementGuid>5287c2f7-4215-4222-8c26-c6fe26b622d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wiki'])[1]/following::button[1]</value>
      <webElementGuid>66061144-ed3d-4d16-bc22-3cf11cbd350e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cài đặt'])[1]/preceding::button[1]</value>
      <webElementGuid>be21908c-32a3-446e-9fa6-b15678b46a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/span/span/button</value>
      <webElementGuid>449a25b4-1eec-4904-b41e-45149ac4d24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Thêm' or . = ' Thêm')]</value>
      <webElementGuid>da3cdac4-a697-4304-a03c-10e3111d1b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
