<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hhhh</name>
   <tag></tag>
   <elementGuidId>6c33aed0-d19e-45d8-8785-853ffb3092ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c887ce40-9b80-4ea6-952c-b92a677f5eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>012e7a53-b179-48e8-a7d9-1c388f2f36b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Viết gì đó chia sẻ cho workspace ...</value>
      <webElementGuid>fb695554-5d7a-4dd6-a01d-6ba66ca7613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6033d1b2-b838-498c-8a2c-7d90be2bb952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-flex-item div-input</value>
      <webElementGuid>428bc190-24d8-4cc6-a1d6-7bc4281e9ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hhhh</value>
      <webElementGuid>4bdaedea-40c9-472e-9ef8-d2fca7c7b2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;child-layout&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;container&quot;]/div[3]/div[1]/div[@class=&quot;create box&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;flex pt-1 pb-1 have-background&quot;]/div[@class=&quot;post-form&quot;]/div[@class=&quot;input-chat full-input&quot;]/div[@class=&quot;not-inline full-input post-create-input&quot;]/div[@class=&quot;input-flex&quot;]/div[@id=&quot;input-text&quot;]</value>
      <webElementGuid>3c738e03-7c68-4f67-a0f2-6aaf700a83c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='input-text']</value>
      <webElementGuid>d371b2bb-d28d-480c-9b37-1e9598927a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>2b21aa39-9acd-4633-9a11-d06de3efc2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi tin nhắn'])[1]/following::div[9]</value>
      <webElementGuid>394a5651-0948-4b0a-a840-986a558bd024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sự kiện mới của Bework'])[1]/following::div[14]</value>
      <webElementGuid>6a9e60c9-d8f1-4577-9779-bd5c02c6e453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phân loại nghiệp vụ'])[1]/preceding::div[14]</value>
      <webElementGuid>80bab32b-c0c6-4128-866e-0741fc395543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design'])[1]/preceding::div[18]</value>
      <webElementGuid>1fc0261e-b07b-485f-8c08-080bffd4826d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hhhh']/parent::*</value>
      <webElementGuid>b1f831e0-4113-4fa9-ae1f-b86faee5315d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>857f5c57-73cb-499f-857c-46f2703dccbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'input-text' and @placeholder = 'Viết gì đó chia sẻ cho workspace ...' and (text() = 'hhhh' or . = 'hhhh')]</value>
      <webElementGuid>d4dd076f-d6a8-4812-b906-51955928dafa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
