<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_viet gi do cho ws</name>
   <tag></tag>
   <elementGuidId>dab02e82-284d-4c87-aa0c-3439b7ddf59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5dda5399-b0b9-4e47-8978-54e3c93023d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>ba4fa3c0-75bd-46b4-9825-a5d7f484223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Viết gì đó chia sẻ cho workspace ...</value>
      <webElementGuid>e929c4f7-e5ac-4017-b52d-ce3158820d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49263718-48cf-4b0b-a7a9-e884c0ebd69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-flex-item div-input</value>
      <webElementGuid>64b2869d-763f-4879-baf9-846825f3647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>viet gi do cho ws</value>
      <webElementGuid>f6db3d51-2ead-476b-9746-0da1c4c144b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;child-layout&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;container&quot;]/div[3]/div[1]/div[@class=&quot;create box&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;flex pt-1 pb-1 have-background&quot;]/div[@class=&quot;post-form&quot;]/div[@class=&quot;input-chat full-input&quot;]/div[@class=&quot;not-inline full-input post-create-input&quot;]/div[@class=&quot;input-flex&quot;]/div[@id=&quot;input-text&quot;]</value>
      <webElementGuid>b9417576-0027-4689-ac1d-6ca7738ad21f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='input-text']</value>
      <webElementGuid>dc00e9a8-f39c-4a77-be79-979ade699f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>f143500c-5087-41f7-9185-1d86f64dfae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gửi tin nhắn'])[1]/following::div[9]</value>
      <webElementGuid>e445afce-3534-4a39-bd2c-36713e928cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sự kiện mới của Bework'])[1]/following::div[14]</value>
      <webElementGuid>c5d8d802-579e-4d78-86df-33819222a00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phân loại nghiệp vụ'])[1]/preceding::div[14]</value>
      <webElementGuid>c9fa7637-7af0-4a43-9e06-6892351d92d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design'])[1]/preceding::div[18]</value>
      <webElementGuid>17070f69-5395-48ea-b84f-cfcf7f891f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='viet gi do cho ws']/parent::*</value>
      <webElementGuid>4ff195ee-723c-49a4-89ee-6b1c6adfd887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>27e4b8ce-5ddb-4ccd-8f28-766e9e832f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'input-text' and @placeholder = 'Viết gì đó chia sẻ cho workspace ...' and (text() = 'viet gi do cho ws' or . = 'viet gi do cho ws')]</value>
      <webElementGuid>5b6b30c6-7bc3-4455-a825-3f7a492eec22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
