<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>75720bc1-51ab-479e-b7d7-3708134352e7</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/span/span/button/span/div/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'logo' and @src = 'https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68fe4bde-828a-4ec8-92c8-30c14cda7c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>3f00a191-f80f-4fea-ab1c-6ce984d1fadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg</value>
      <webElementGuid>36c748d4-9d51-4c0f-9f55-05a1cdf254d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg</value>
      <webElementGuid>61eb3adf-e42f-4a77-959e-90fd68e6c80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>07e8404f-7163-4c74-b891-ff6ab131b501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;side-menu&quot;]/div[@class=&quot;user-info el-row&quot;]/span[1]/span[@class=&quot;el-popover__reference-wrapper&quot;]/button[@class=&quot;el-button is-create-color is-white is-none-border icon-btn p-0 m-0 el-button--default el-popover__reference&quot;]/span[1]/div[@class=&quot;custom-avatar div-place-img div-img-ssm round&quot;]/img[1]</value>
      <webElementGuid>ba0a8c14-c406-4a72-9b31-f29fb4ca84ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/span/span/button/span/div/img</value>
      <webElementGuid>a560ac74-5002-4d4c-a157-c7784d4c9fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>4c276134-1f5c-420b-9394-23ee7563419c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8fb99129-72f7-4d34-bde0-1694001d5647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo' and @src = 'https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg']</value>
      <webElementGuid>0efc5001-b5de-4673-99db-73eb34f20dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div[2]/div[2]/div[2]/div/ul/li[2]/a/img</value>
      <webElementGuid>c0dc3b65-6cd8-4c85-a1d0-dcc4dabc5b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[5]</value>
      <webElementGuid>5edaeae3-9525-49dd-928d-74beab08f0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>63588ce4-4245-4bc5-bc27-f041dd1397f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bework-production.s3.cloud.cmctelecom.vn/default/post/bg1.jpg' and @alt = 'logo']</value>
      <webElementGuid>7ee978ea-f1a4-493e-b818-8ce3bd837da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
