<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>8e233afe-5603-48de-880e-ef472e44ad93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/span/span/button/span/div/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg' and @alt = 'logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7cc3a7dc-bea6-4413-834f-338884d74f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg</value>
      <webElementGuid>4307ea12-72b1-4b82-bd39-23d9e824edfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>43eacf1b-b711-45b4-9495-c0e91d243e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;side-menu&quot;]/div[@class=&quot;user-info el-row&quot;]/span[1]/span[@class=&quot;el-popover__reference-wrapper&quot;]/button[@class=&quot;el-button is-create-color is-white is-none-border icon-btn p-0 m-0 el-button--default el-popover__reference&quot;]/span[1]/div[@class=&quot;custom-avatar div-place-img div-img-ssm round&quot;]/img[1]</value>
      <webElementGuid>e35d3355-8e02-4c9d-a7ff-f6e94545a740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg</value>
      <webElementGuid>f42952bd-7465-4978-91da-45d39e16a115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>1b2c9ec1-f148-4816-9563-441498b7bf23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/span/span/button/span/div/img</value>
      <webElementGuid>c1e8b484-6486-4473-9b08-19a6d826513f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>b7939e9f-bca5-4c1a-876a-eb1277cc2a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5aafeccf-96b4-4a54-9d84-2edb44dab250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo' and @src = 'https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7044_1675703216651.jpg']</value>
      <webElementGuid>ac26a2dc-a4da-4be1-a9a1-dc72fb33c574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div[2]/div[2]/div[2]/div/ul/li[2]/a/img</value>
      <webElementGuid>53ee4ec9-3de5-4534-a0c1-93afe86685da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[5]</value>
      <webElementGuid>11b4e9d0-2e72-46b0-9e9b-cfc09c8c37b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>36cb9aa1-1c62-4f5b-9905-48226b34a338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bework-production.s3.cloud.cmctelecom.vn/default/post/bg1.jpg' and @alt = 'logo']</value>
      <webElementGuid>b3f7d6f1-519c-45d8-8c3e-2e528df58412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
