<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>abd7e2f2-880e-4cba-8fae-aa59b03cb633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div[2]/div[2]/div[2]/div/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > img[alt=&quot;logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c2b27ace-fad6-4ad6-b9d2-9e1ccdb97bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bework-production.s3.cloud.cmctelecom.vn/default/post/bg1.jpg</value>
      <webElementGuid>140fc459-9720-4957-b6d2-682ac70bc408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>874e6640-8ff0-4dbe-bafe-dbc1f8fe51fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;child-layout&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;container&quot;]/div[3]/div[1]/div[@class=&quot;create box&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;flex pt-1 pb-1&quot;]/div[@class=&quot;post-form&quot;]/div[@class=&quot;post-background post-bg-button&quot;]/div[@class=&quot;flex-left-right&quot;]/ul[@class=&quot;flex-left-right list-background&quot;]/li[2]/a[1]/img[1]</value>
      <webElementGuid>f40d60c0-a458-456c-a96b-abf8f1abf02d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div[2]/div[2]/div[2]/div/ul/li[2]/a/img</value>
      <webElementGuid>3589ef01-e2e5-45ef-933e-d7fae48a4ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[5]</value>
      <webElementGuid>8bd7fc6c-bd0b-4856-9710-ba7eaaeec7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>19c8b257-a58b-48b2-b5ac-214a7975085a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bework-production.s3.cloud.cmctelecom.vn/default/post/bg1.jpg' and @alt = 'logo']</value>
      <webElementGuid>8912f219-9287-4e1d-a50b-cc5d356d6429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
