<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thay i mt khu_oldPassword</name>
   <tag></tag>
   <elementGuidId>f1e65f95-66d3-487d-8ce1-4d7eb51d1c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='oldPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;oldPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca961d49-1c8e-449d-bcdf-615104b16199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d5f03014-4f62-46ad-9beb-597327ab5309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>257492be-0982-4352-88ca-d637f749f67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oldPassword</value>
      <webElementGuid>e64aa209-7527-4428-a0b4-7af602bce37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu cũ</value>
      <webElementGuid>590bac90-8b95-4132-b0e9-d624b3ac5493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>6bc58661-cf79-4ea7-be9b-a3bb6c228b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;el-dialog__wrapper&quot;]/div[@class=&quot;el-dialog dialog-padding-unset&quot;]/div[@class=&quot;el-dialog__body&quot;]/div[@class=&quot;s-dialog-content s-dialog-scroll-style&quot;]/div[@class=&quot;el-row&quot;]/div[@class=&quot;content s-dialog-scroll-style scroll-style el-col el-col-18&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;el-form el-form--label-left&quot;]/div[@class=&quot;el-form-item is-required&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-input&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>9c43e313-2303-4c83-a1e7-cac0cdd783ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='oldPassword']</value>
      <webElementGuid>9b2bed08-943e-4676-ba3a-f6fa6b5e9751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>a9abb3d2-61e0-4e47-acfc-9fe173741450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'oldPassword' and @placeholder = 'Mật khẩu cũ']</value>
      <webElementGuid>87c1cacd-11fa-49fc-a4fa-d6cdbbf5692b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
