<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Giao cho_el-input__inner</name>
   <tag></tag>
   <elementGuidId>15d73fc0-a007-4eb2-964a-213e034a9066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.el-input.el-input--prefix.el-input--suffix.is-focus > input.el-input__inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>286001de-6e7d-4b09-95b8-ef000f68a3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc6a9b26-0912-4f8a-9138-3d94cc04980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>361b4706-bbac-431a-9824-f6f59d7a19b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nguyen Thi Huyen</value>
      <webElementGuid>6c8eba3b-a3a0-4fcc-aef7-dce72be4381e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>efb0ad84-96a1-4d86-b046-3c0f66d7ba88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bt-edit-form&quot;)/form[@class=&quot;el-form bt-custom-add-task el-form--label-left mt-1&quot;]/div[@class=&quot;el-form-item bt-error-add-task&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-select bt-custom-select-placeholder bt-add-task-field bt-add-task-assign bt-form-item-asana bt-form-has-padding&quot;]/div[@class=&quot;el-input el-input--prefix el-input--suffix is-focus&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>d9b8d494-dee1-4c8a-83e1-59e8bc95769d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>fb0ca6e0-1ff5-4d3d-9469-ad041c42b648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bt-edit-form']/form/div[3]/div/div/div/input</value>
      <webElementGuid>7fe73016-b0aa-4ba5-b4be-94c9340b6eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/div/input</value>
      <webElementGuid>87ebb4a7-0269-4926-8acb-9f8ee1542563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nguyen Thi Huyen']</value>
      <webElementGuid>46f24af5-a655-4f25-a15d-4769d5933354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
