<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_D n_project</name>
   <tag></tag>
   <elementGuidId>34d49e29-db03-42bb-a107-984ef791c940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;project&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='project']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69ee1070-2ae9-4e81-a501-adbb346f67b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8663fbb-554f-4858-93b2-a6dd12a25fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4dd094fd-ad09-4004-a5f6-b7df3a3848ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Chọn dự án</value>
      <webElementGuid>f0aeafb3-f53f-4c68-9c84-0fd78c0a5401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>project</value>
      <webElementGuid>42c428bc-59ed-47f0-86a1-5d95154efe81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>d4dac2ce-920d-4795-ad8d-c09ee6f371cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bt-edit-form&quot;)/form[@class=&quot;el-form bt-custom-add-task el-form--label-left mt-1&quot;]/div[@class=&quot;be-task-align-item-center bt-mb-15px&quot;]/div[@class=&quot;el-form-item mb-0 bt-project-select betask-box-select&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-select select-no-border bt-custom-select-placeholder bt-add-task-field&quot;]/div[@class=&quot;el-input el-input--suffix is-focus&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>c038ae0c-c1e9-4c10-bf71-876d31d642f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='project']</value>
      <webElementGuid>a61c8c3d-50c6-4008-b785-71b7bf2efdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bt-edit-form']/form/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>005f9910-9e19-436b-913a-4bc45946dd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>146f6abb-c231-4b1a-acdc-717d68bb013e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Chọn dự án' and @name = 'project']</value>
      <webElementGuid>9cd09534-1785-4872-92d7-7a76f228810e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
