<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_To do</name>
   <tag></tag>
   <elementGuidId>c3adca7f-9a02-4219-8827-d7347c2fc90e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-menu-4315']/li[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'To do' or . = 'To do')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6acb9f8f-013c-4ecf-a732-8d595525076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>80a02a78-c32d-4b6b-a53f-870c948f2bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-dropdown-menu__item</value>
      <webElementGuid>9a9f30c1-aa99-47ec-b77a-463dd3f954a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>To do</value>
      <webElementGuid>36c2734f-7821-4fae-9c45-fdc3a10c5934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-4315&quot;)/li[@class=&quot;el-dropdown-menu__item&quot;]</value>
      <webElementGuid>a45e355c-84d0-4fb0-830a-2250236e483e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-menu-4315']/li[2]</value>
      <webElementGuid>5de0e89a-ac32-4857-bd98-151bccc0d46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backlog'])[2]/following::li[1]</value>
      <webElementGuid>9d446285-401d-4568-b8af-56888f4e7aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tt'])[12]/following::li[2]</value>
      <webElementGuid>b4dacae0-b4f7-4c33-90ab-8e56ace20188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doing'])[1]/preceding::li[1]</value>
      <webElementGuid>9db074a6-71ab-4963-9998-b48a12cd8ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::li[2]</value>
      <webElementGuid>5d581a5d-459b-4efa-87a9-8916cb291594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='To do']/parent::*</value>
      <webElementGuid>7386ea5f-844d-40a6-b94a-bf0c06b77753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]</value>
      <webElementGuid>0941553a-c80b-4c2c-8373-ce1509c23fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'To do' or . = 'To do')]</value>
      <webElementGuid>48942b81-3c32-4b50-bbc4-bb287322cd3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
