<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Backlog</name>
   <tag></tag>
   <elementGuidId>2f1564b3-5f7b-4efe-beb9-db94781c2005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.el-dropdown-link.cursor-pointer.bt-custom-dropdown.el-dropdown-selfdefine.focusing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bt-edit-form']/form/div[2]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>34ed0b7e-f7a5-4f71-a84a-76bec83519e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-dropdown-link cursor-pointer bt-custom-dropdown el-dropdown-selfdefine focusing</value>
      <webElementGuid>de8cfad9-805a-457a-936c-51fd93bdf480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c82cc6c4-9633-43ce-a7b7-dba2309fc6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-menu-4315</value>
      <webElementGuid>8c3fbb1e-277e-45a1-9ab0-7582fdf2a608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ae91b81-415c-4749-94da-9692daf7c9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>273b7ec7-7f84-49d0-bf8c-cf63cfd2f8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Backlog</value>
      <webElementGuid>3633694f-fc59-412f-80e2-0241bc6dce7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bt-edit-form&quot;)/form[@class=&quot;el-form bt-custom-add-task el-form--label-left mt-1&quot;]/div[@class=&quot;be-task-align-item-center bt-mb-15px&quot;]/div[@class=&quot;el-dropdown&quot;]/span[@class=&quot;el-dropdown-link cursor-pointer bt-custom-dropdown el-dropdown-selfdefine focusing&quot;]</value>
      <webElementGuid>413727b3-44a7-4dd8-8d16-8aa6635d5808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bt-edit-form']/form/div[2]/div[3]/span</value>
      <webElementGuid>b19ae3df-0903-4f5a-be97-1d364698f469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dự án'])[2]/following::span[4]</value>
      <webElementGuid>6866c6cf-1f94-440b-ba3c-5863dac757f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo công việc mới'])[1]/following::span[4]</value>
      <webElementGuid>9018a6a6-06cd-45d2-8801-1ab4fd75f7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backlog'])[2]/preceding::span[1]</value>
      <webElementGuid>19afe334-df84-4c97-92ef-a29b5e4d207e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To do'])[1]/preceding::span[1]</value>
      <webElementGuid>3266978f-7fd7-43c4-bd78-bcf072513c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Backlog']/parent::*</value>
      <webElementGuid>b975983d-45c9-463e-80a6-f09be951310a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span</value>
      <webElementGuid>8b8837d5-add4-43a0-b7ed-bdd23ff26e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            Backlog' or . = '
            Backlog')]</value>
      <webElementGuid>620c96ca-1004-4a7f-86cf-29a782925685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
