<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_To cng vic mi_title</name>
   <tag></tag>
   <elementGuidId>57d931fd-3af8-4823-a3a5-b5684f3035d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;title&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>634ef5df-d907-4c58-9473-408cdcd802bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>18999704-d581-47ce-b66d-113627e9d428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>a23f8a12-40ad-4c95-9ae9-56d3c3091ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên công việc</value>
      <webElementGuid>50ac4bf0-8102-4b4d-a8d6-6a42ae57f0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-textarea__inner</value>
      <webElementGuid>94bc1f14-31ab-40af-902f-1873a3343b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bt-edit-form&quot;)/form[@class=&quot;el-form bt-custom-add-task el-form--label-left mt-1&quot;]/div[@class=&quot;el-form-item bt-form-item-asana bt-title-task-edit is-error is-required&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-textarea&quot;]/textarea[@class=&quot;el-textarea__inner&quot;]</value>
      <webElementGuid>f156a84e-c040-402d-a78d-ab3236944c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='title']</value>
      <webElementGuid>d60ed0b9-10d1-43ac-9f39-83d1cf79cff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bt-edit-form']/form/div/div/div/textarea</value>
      <webElementGuid>7d1b6dbf-03e1-4589-bc71-c5045135da66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f4d7ee74-98fa-4c8e-8a0b-48f97cf58121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'title' and @placeholder = 'Tên công việc']</value>
      <webElementGuid>7b20fe98-ed26-47b4-b395-0253d06a4f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
